dist: xenial
language: c
filter_secrets: false
cache:
  - ccache
  - apt
before_script:
  - export -f travis_fold
script:
  - travis_fold start "build"
  - bash -e ./.travis-install.sh && bash -e ./.travis-script.sh
  - travis_fold end "build"
  # Add arm(32) build only for linux/arm64 instance
  - travis_fold start "build.arm32"
  - git clean -dfx
  - if [ $TRAVIS_ARCH == "aarch64" ] && [ $TRAVIS_OS_NAME == "linux" ] ; then ARCH=arm RUMPRUN_TOOLCHAIN_TUPLE=arm-rumprun-linux bash -e ./.travis-install.sh ; ARCH=arm bash -e ./.travis-script.sh ; fi
  - travis_fold end "build.arm32"

os:
  - osx
  - linux

arch:
  - amd64
  - arm64

stages:
  - test
  - deploy

jobs:
  exclude:
    - os: osx
      arch: arm64
    # broken: issue #106
    - env: PACKAGE=mysql
    # broken: issue #92
    - env: PACKAGE=openmp
    # Disabled, does not actually build anything interesting
    - env: PACKAGE=roundcube
    # Disabled, build takes several hours
    - env: PACKAGE=rust
    # for shorten tests
    - env: PACKAGE=erlang
    - env: PACKAGE=haproxy
    - env: PACKAGE=hiawatha
    - env: PACKAGE=leveldb
    - env: PACKAGE=libcurl
    - env: PACKAGE=libevent
    - env: PACKAGE=libressl
    - env: PACKAGE=libxml2
    - env: PACKAGE=mathopd
    - env: PACKAGE=memcached
    - env: PACKAGE=mpg123
    - env: PACKAGE=nanomsg
    - env: PACKAGE=ngircd
    - env: PACKAGE=pcre
    - env: PACKAGE=php5
    - env: PACKAGE=php7
    - env: PACKAGE=ruby
    - env: PACKAGE=sqlite
    - env: PACKAGE=sqlite-bench
    - env: PACKAGE=tor
    - env: PACKAGE=apache2
    - env: PACKAGE=libffi
    - env: PACKAGE=openjdk8
    - env: PACKAGE=ovs
    - env: PACKAGE=zeromq
    - env: PACKAGE=servus
    - env: PACKAGE=zerobuf
  include:
    - stage: deploy
      script:
        - bash -e ./.travis-deploy-docker.sh
        - bash -e ./.travis-trigger.sh ukontainer/runu
      os: linux
      dist: trusty  # XXX: docker multi-arch image requires 17.09(dockerd):18.06(docker)
      env: RUMPKERNEL=linux
  allow_failures:
    # no crypto.a
    - env: PACKAGE=erlang
    # no toolchain.cmake
    - env: PACKAGE=hiawatha
    # no g++
    - env: PACKAGE=leveldb
    # no audio_info_t
    - env: PACKAGE=mpg123
    # no Get_Error
    - env: PACKAGE=ngircd
    # no libz
    - env: PACKAGE=php5
    # no libz
    - env: PACKAGE=tor
    # no same as netbsd (404)
    - env: PACKAGE=apache2
    # no g++
    - env: PACKAGE=openjdk8
    # no net/if_packet.h
    - env: PACKAGE=ovs
    # no g++
    - env: PACKAGE=zeromq
    # no g++
    - env: PACKAGE=servus
    # no g++
    - env: PACKAGE=zerobuf
    # osx (TO_BE_FIXED)
    - env: PACKAGE=libevent
      os: osx
    - env: PACKAGE=libressl
      os: osx
    - env: PACKAGE=libxml2
      os: osx
    - env: PACKAGE=mathopd
      os: osx
    - env: PACKAGE=memcached
      os: osx
    - env: PACKAGE=php7
      os: osx
    - env: PACKAGE=ruby
      os: osx
    - env: PACKAGE=libffi
      os: osx
    # Unsupported CPU architecture
    - env: PACKAGE=nodejs
      arch: arm64

env:
  global:
    - PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:/opt/rump/bin:$PATH"
    - RUMPKERNEL=linux
  jobs:
    - PACKAGE=erlang
    - PACKAGE=haproxy
    - PACKAGE=hiawatha
    - PACKAGE=leveldb
    - PACKAGE=libcurl
    - PACKAGE=libevent
    - PACKAGE=libressl
    - PACKAGE=libxml2
    - PACKAGE=mathopd
    - PACKAGE=memcached
    - PACKAGE=mpg123
    - PACKAGE=mysql
    - PACKAGE=nanomsg
    - PACKAGE=netperf
    - PACKAGE=nginx
    - PACKAGE=ngircd
    - PACKAGE=nodejs
    - PACKAGE=openmp
    - PACKAGE=pcre
    - PACKAGE=php5
    - PACKAGE=php7
    - PACKAGE=python3
    - PACKAGE=redis
    - PACKAGE=roundcube
    - PACKAGE=ruby
    - PACKAGE=rust
    - PACKAGE=sqlite
    - PACKAGE=sqlite-bench
    - PACKAGE=tor
    - PACKAGE=apache2
    - PACKAGE=libffi
    - PACKAGE=openjdk8
    - PACKAGE=ovs
    - PACKAGE=zeromq
    - PACKAGE=servus
    - PACKAGE=zerobuf


      # notifications:
      #   irc:
      #     channels:
      #       - "chat.freenode.net#rumpkernel-builds"
      #     template:
      #       - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
      #     skip_join: true
      #     use_notice: true
      #   email:
      #     recipients:
      #       - rumpkernel-builds@freelists.org
      #     on_success: always
      #     on_failure: always

