sudo: required
dist: xenial
language: generic
cache:
  directories:
    - $HOME/.ccache
script: bash -ex ./.travis-install.sh && bash -ex ./.travis-script.sh

os:
  - osx
  - linux

arch:
  - amd64
  - arm64

stages:
  - test
  - deploy

jobs:
  exclude:
    - os: osx
      arch: arm64
  include:
    - stage: deploy
      script:
        - bash -ex ./.travis-deploy-docker.sh
        - bash -ex ./.travis-trigger.sh ukontainer/runu
      os: linux
      env: RUMPKERNEL=linux

env:
  global:
    - PATH="/usr/lib/ccache:/opt/rump/bin:$PATH"
  matrix:
          #     - PACKAGE=erlang RUMPKERNEL=netbsd
          #     - PACKAGE=haproxy RUMPKERNEL=netbsd
          #     - PACKAGE=hiawatha RUMPKERNEL=netbsd
          #     - PACKAGE=leveldb RUMPKERNEL=netbsd
          #     - PACKAGE=libcurl RUMPKERNEL=netbsd
          #     - PACKAGE=libevent RUMPKERNEL=netbsd
          #     - PACKAGE=libressl RUMPKERNEL=netbsd
          #     - PACKAGE=libxml2 RUMPKERNEL=netbsd
          #     - PACKAGE=mathopd RUMPKERNEL=netbsd
          #     - PACKAGE=memcached RUMPKERNEL=netbsd
          #     - PACKAGE=mpg123 RUMPKERNEL=netbsd
          #   # broken: issue #106
          #   #  - PACKAGE=mysql RUMPKERNEL=netbsd
          #     - PACKAGE=nanomsg RUMPKERNEL=netbsd
          #     - PACKAGE=netperf RUMPKERNEL=netbsd
          #     - PACKAGE=nginx RUMPKERNEL=netbsd
          #     - PACKAGE=ngircd RUMPKERNEL=netbsd
          #     - PACKAGE=nodejs RUMPKERNEL=netbsd
          #   # broken: issue #92
          #   #  - PACKAGE=openmp RUMPKERNEL=netbsd
          #     - PACKAGE=pcre RUMPKERNEL=netbsd
          #     - PACKAGE=php5 RUMPKERNEL=netbsd
          #     - PACKAGE=php7 RUMPKERNEL=netbsd
          #     - PACKAGE=python3 RUMPKERNEL=netbsd
          #     - PACKAGE=redis RUMPKERNEL=netbsd
          #   # Disabled, does not actually build anything interesting
          #   #  - PACKAGE=roundcube RUMPKERNEL=netbsd
          #     - PACKAGE=ruby RUMPKERNEL=netbsd
          #   # Disabled, build takes several hours
          #   #  - PACKAGE=rust RUMPKERNEL=netbsd
          #     - PACKAGE=sqlite RUMPKERNEL=netbsd
          #     - PACKAGE=sqlite-bench RUMPKERNEL=netbsd
          #     - PACKAGE=tor RUMPKERNEL=netbsd
          #     - PACKAGE=apache2 RUMPKERNEL=netbsd
          #     - PACKAGE=libffi RUMPKERNEL=netbsd
          #     - PACKAGE=openjdk8 RUMPKERNEL=netbsd
          #     - PACKAGE=ovs RUMPKERNEL=netbsd
          #     - PACKAGE=zeromq RUMPKERNEL=netbsd
          #     - PACKAGE=servus RUMPKERNEL=netbsd
          #     - PACKAGE=zerobuf RUMPKERNEL=netbsd
###    - PACKAGE=erlang RUMPKERNEL=linux
###    - PACKAGE=haproxy RUMPKERNEL=linux
###    - PACKAGE=hiawatha RUMPKERNEL=linux
###    - PACKAGE=leveldb RUMPKERNEL=linux
###    - PACKAGE=libcurl RUMPKERNEL=linux
###    - PACKAGE=libevent RUMPKERNEL=linux
###    - PACKAGE=libressl RUMPKERNEL=linux
###    - PACKAGE=libxml2 RUMPKERNEL=linux
###    - PACKAGE=mathopd RUMPKERNEL=linux
###    - PACKAGE=memcached RUMPKERNEL=linux
###    - PACKAGE=mpg123 RUMPKERNEL=linux
###  # broken: issue #106
###  #  - PACKAGE=mysql RUMPKERNEL=linux
###    - PACKAGE=nanomsg RUMPKERNEL=linux
    - PACKAGE=netperf RUMPKERNEL=linux
    - PACKAGE=nginx RUMPKERNEL=linux
###    - PACKAGE=ngircd RUMPKERNEL=linux
    - PACKAGE=nodejs RUMPKERNEL=linux
###  # broken: issue #92
###  #  - PACKAGE=openmp RUMPKERNEL=linux
###    - PACKAGE=pcre RUMPKERNEL=linux
###    - PACKAGE=php5 RUMPKERNEL=linux
###    - PACKAGE=php7 RUMPKERNEL=linux
###  # no libz
    - PACKAGE=python3 RUMPKERNEL=linux
    - PACKAGE=redis RUMPKERNEL=linux
###  # Disabled, does not actually build anything interesting
###  #  - PACKAGE=roundcube RUMPKERNEL=linux
###    - PACKAGE=ruby RUMPKERNEL=linux
###  # Disabled, build takes several hours
###  #  - PACKAGE=rust RUMPKERNEL=linux
###    - PACKAGE=sqlite RUMPKERNEL=linux
###    - PACKAGE=sqlite-bench RUMPKERNEL=linux
###    - PACKAGE=tor RUMPKERNEL=linux
###    - PACKAGE=apache2 RUMPKERNEL=linux
###    - PACKAGE=libffi RUMPKERNEL=linux
###    - PACKAGE=openjdk8 RUMPKERNEL=linux
###    - PACKAGE=ovs RUMPKERNEL=linux
###    - PACKAGE=zeromq RUMPKERNEL=linux
###    - PACKAGE=servus RUMPKERNEL=linux
###    - PACKAGE=zerobuf RUMPKERNEL=linux

matrix:
  allow_failures:
# no crypto.a
    - env: PACKAGE=erlang RUMPKERNEL=linux
# no toolchain.cmake
    - env: PACKAGE=hiawatha RUMPKERNEL=linux
# no g++
    - env: PACKAGE=leveldb RUMPKERNEL=linux
# no audio_info_t
    - env: PACKAGE=mpg123 RUMPKERNEL=linux
# no Get_Error
    - env: PACKAGE=ngircd RUMPKERNEL=linux
# no libz
    - env: PACKAGE=php5 RUMPKERNEL=linux
# no libz
    - env: PACKAGE=tor RUMPKERNEL=linux
# no same as netbsd (404)
    - env: PACKAGE=apache2 RUMPKERNEL=linux
# no g++
    - env: PACKAGE=openjdk8 RUMPKERNEL=linux
# no net/if_packet.h
    - env: PACKAGE=ovs RUMPKERNEL=linux
# no g++
    - env: PACKAGE=zeromq RUMPKERNEL=linux
# no g++
    - env: PACKAGE=servus RUMPKERNEL=linux
# no g++
    - env: PACKAGE=zerobuf RUMPKERNEL=linux
# osx (TO_BE_FIXED)
    - env: PACKAGE=libevent RUMPKERNEL=linux
      os: osx
    - env: PACKAGE=libressl RUMPKERNEL=linux
      os: osx
    - env: PACKAGE=libxml2 RUMPKERNEL=linux
      os: osx
    - env: PACKAGE=mathopd RUMPKERNEL=linux
      os: osx
    - env: PACKAGE=memcached RUMPKERNEL=linux
      os: osx
    - env: PACKAGE=php7 RUMPKERNEL=linux
      os: osx
    - env: PACKAGE=redis RUMPKERNEL=linux
      os: osx
    - env: PACKAGE=ruby RUMPKERNEL=linux
      os: osx
    - env: PACKAGE=libffi RUMPKERNEL=linux
      os: osx
    # Unsupported CPU architecture
    - env: PACKAGE=nodejs RUMPKERNEL=linux
      arch: arm64
    - env: PACKAGE=redis RUMPKERNEL=linux
      arch: arm64

      # notifications:
      #   irc:
      #     channels:
      #       - "chat.freenode.net#rumpkernel-builds"
      #     template:
      #       - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
      #     skip_join: true
      #     use_notice: true
      #   email:
      #     recipients:
      #       - rumpkernel-builds@freelists.org
      #     on_success: always
      #     on_failure: always

